spring:
  # To See H2 Console in Browser:
  # http://localhost:8080/h2-console
  # Enabling H2 Console
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb

  jpa:
    show-sql: true
